### ISSUE TITLE
Corrupt Heap 

### ISSUE THREAD

**Issue by giorgio80** [mobizt/Firebase-ESP32#149]
**Describe the bug**
getting corrupt heap on document writing 
**To Reproduce**

unfortunately I cannot reproduce it as it seems to be random but I espExceptiondecoder the output

**Expected behavior**
during running an update esp32 simply hangs and restart 

**Screenshots**

https://i.postimg.cc/nhNK2hbC/Screenshot-2021-02-24-at-11-46-03.png

**IDE and its version:**
 Using platform with latest espressif version of idf (2.0)

**Comment by mobizt** [comment]
You should provide the code and check your free memory before calling Firebase functions.
No thing can help based on your info.

**Comment by giorgio80** [comment]
is what I 'm doing, 

btw indicating seems related to function: 

void FirebaseESP32::delS(char *p)
{
  if (p != nullptr)
    delete[] p;
}


it seems to hangs when launch the delete[] p

can I ask you what's the role of this function to start debugging ?

**Comment by mobizt** [comment]
I don't understand what you are trying to do.

Please learn the basic C or C++ programming.

**Comment by mobizt** [comment]
The error from decoded trace is about dynamic memory allocation by calling **new** to allocate the memory then the **delete** was called to free the memory.

The error may occur when not enough memory for allocation with the desired amount due to you misused the stream.

The data at that node in the database which  you're trying to stream is too large to handle by the limited memory device.

You should reduce the data to get from stream.

**Comment by mobizt** [comment]
You should also update the ESP32 Core SDK.
