### ISSUE TITLE
data.eventType() always returns "put"

### ISSUE THREAD

**Issue by casvanluijtelaar** [mobizt/Firebase-ESP32#153]
**Describe the bug**
No matter what action is taken on the realtime database when printing the `StreamData` `dataType()` method it will always return "put"

**To Reproduce**
1. run `stream_callback` example
2. delete entry from your realtime database.
3. observe `data.eventType()` print
4. any action returns "put"

**Expected behavior**
It's very important to me to see a clear distinction between "put" and delete" events. 

**Screenshots**

**IDE and its version:**
 - Arduino
 - Version [1.8.13]

**Comment by mobizt** [comment]
Please ask if you have the question or problem instead of set this issue to bug.

The event type is issued by Google not the library.

There are only 5 events that available from RTDB stream i.e. put, patch, keep-alive, cancel and auth_revoke.

Please read [this doc](https://firebase.google.com/docs/reference/rest/database#section-streaming) for reference
