### ISSUE TITLE
HELP: Which verison is the most stable for long term use?

### ISSUE THREAD

**Issue by 0100101101001011** [mobizt/Firebase-ESP32#158]
Hi! First of all, this library is AMAZING!

We are implementing this library in several of our projects. In our applications, we mainly use the Stream Callbacks functions of this library. 

We have noticed this library gets frequent updates which are really great. But in our implemented project, certain conditions prohibit us from rolling out regular OTA firmware updates to our in-field devices. So which version of this library is most suitable for long-term no-update use? And how often should we be following the updates of this library?

Thanks!

**Comment by mobizt** [comment]
The update is based on the opened issues, feature request and bugs that I've found and no planning with the bugs fix.

Some issue is just discovered by specific usage and need urgently update.


FYI.  The latest version is most stable if you're using stream callback , unless you are manually reading  the stream in the loop(). which currently found the bug in stream available status reporting, since v3.8.18.

If you're using the stream callback, this bug is not affected and you can use v3.8.26.

The library is open source which you can fork and modify it if you want to make your custom version.
