### ISSUE TITLE
Firebase library for STM32 Boards 

### ISSUE THREAD

**Issue by mrajaraghavan** [mobizt/Firebase-ESP32#181]
Hi,
I have tested your library with ESP32 and ESP32S2 board in Arduino IDE and it works smoothly.. 

I appreciate your efforts.🤝

I wanted to use this library or a similar library in STM32L4 series boards in STM32CubeIDE… but as on today there is no library available in the net. 

Do u have an interest to develop the same … or can you advise some tips to develop a library for firebase and STM boards ?

I came across AWS, Azure have some library and examples to interface STM boards 

Thanks

**Comment by mobizt** [comment]
Due to hardware variant, most of them don't have native internet access and depended on external SPI and PHY module, the development needs the driver integrated with SSL.

In addition it requires encryption/decryption provided by SSL library to use in token generation.

Due to full of works in hands and above requirement need times for implement then this is not plan in the near future. 

You can follow the Firebase REST API doc that available from google and use the already available of curl or http client libraries that are available for that platform.
