### ISSUE TITLE
How to push a value with a timestamp in the same key?

### ISSUE THREAD

**Issue by 0x776172** [mobizt/Firebase-ESP32#188]
Hi sir, i want to add timestamp in my value. look like this:
![image](https://user-images.githubusercontent.com/73809668/131428027-7e0f67de-bb01-4fa2-a4bb-9e819caedc22.png)

json1.add("Value", valLight);
json1.add("TImestamp", Firebase.pushTimestamp(fbdo, ""));
Firebase.pushJSON(fbdo, pathJSON, json1);

i have tried this code but it doesnt work properly, and the return of the Firebase.pushTimestamp is false with the error of bad request.. please help me with the issues.

**Comment by mobizt** [comment]
You should read the document for function descriptions.

All functions returned boolean for the operrating status instead of value.

For the pushTimestamp function, there is a bug that returns bad request which was already fixed, please update the library to latest version, [v3.11.3](https://github.com/mobizt/Firebase-ESP32/releases/tag/v3.11.3).

With the latest version library, the timestamp example was updated which you can follow how to set and get the timestamp correctly.
https://github.com/mobizt/Firebase-ESP32/blob/master/examples/Timestamp/Timestamp.ino

**Comment by 0x776172** [comment]
Thank you very much, i will try the code soon!

**Comment by 0x776172** [comment]
> You should read the document for function descriptions.
> 
> All functions returned boolean for the operating status instead of value.
> 
> For the pushTimestamp function, there is a bug that returns bad request which was already fixed, please update the library to latest version, [v3.11.3](https://github.com/mobizt/Firebase-ESP32/releases/tag/v3.11.3).
> 
> With the latest version library, the timestamp example was updated which you can follow how to set and get the timestamp correctly.
> https://github.com/mobizt/Firebase-ESP32/blob/master/examples/Timestamp/Timestamp.ino

okay i will try the code, Thank you very much!!
