### ISSUE TITLE
BUG - Streaming doesn't recognize the firebase field name properly if it starts with a number.

### ISSUE THREAD

**Issue by Finthugo** [mobizt/Firebase-ESP32#190]
Hello all,

We have been using the Firebase-ESP32 library and we found what it seems to be a quite strange bug.

Basically the streaming doesn't recognize the firebase field name properly if it starts with a number.

For example, if you use the lines:
Firebase.beginStream(stream, "\MMMMM");
or
Firebase.beginStream(stream, "\i00124");

The system will work properly and the debug line Serial.println(data.streamPath()); will display: /MMMMM

BUT 

If you use the lines:
Firebase.beginStream(stream, "\1MMMMM");
or
Firebase.beginStream(stream, "\00124");

IT WON'T WORK and and the debug line Serial.println(data.streamPath()); will display: /24

I know this is quite easy to "solve" this issue by reprogramming all ESPs and changing all database names to start with a letter (which will be pretty hard in our case). But is there something that we can do to solve this without reprogramming the ESPs ? Like changing the name fields on firebase for something that will make the ESPs recognize /00124 properly ?

I am really thankful for any help you can provide.

**Comment by mobizt** [comment]
With the string that contains \, the back slash is the escape sequence of character followed it.

If you don't know what is escape sequence, [read this](https://en.wikipedia.org/wiki/Escape_sequences_in_C).

For example when you create string literal like this "\1abcd", the string will consist of 4 bytes length char array.

The value from first to last byte is 1, 97, 98, 99. Note that ,the "a" character has value of 97 in ASCII table.

You will see that string "\1" has one byte length with value 1  as \ escape its value of followed character "1" to interpret or compile as the value of 1 instead of 49 or "1" in ASCII table.

The back slash is not the one in prohibit characters that can't use in key or value of Firebase RTDB as state [here](https://firebase.google.com/docs/database/rest/structure-data), unless "\0",  "\1", "\2" etc. is correspond to the byte value of 0, 1, 2 which are in the range of control characters (0-31) and 127, which are invalid to use with Firebase RTDB's key and value.

If you test enough, you will find what is the error reason when you include such invalid characters in to the path and value.

The sever will return HTTP code **400 Bad Request** with the following payload 

```json
{
  "error" : "Invalid path: Invalid token in path"
}
```

When you print string "\1" in serial, you will see unrecognized character (not numeric or alphabet) in the serial.
