### ISSUE TITLE
Unable to connect Bluetooth and wifi simultaneously

### ISSUE THREAD

**Issue by Karandalwani** [mobizt/Firebase-ESP32#214]
This is to inform you that whenever I try to connect bluetooth and wifi simultaneously with firebase it gives error like this 

Guru Meditation Error: Core  0 panic'ed (StoreProhibited). Exception was unhandled.
Core 0 register dump:
PC      : 0x4000c46c  PS      : 0x00060a30  A0      : 0x80163986  A1      : 0x3fff5bf0  
A2      : 0x00000000  A3      : 0x00000000  A4      : 0x0000001c  A5      : 0x00000000  
A6      : 0x401ff7f0  A7      : 0x00000001  A8      : 0x80152069  A9      : 0x3fff5b90  
A10     : 0x3ffff54c  A11     : 0x00000044  A12     : 0x00000000  A13     : 0x00000000  
A14     : 0x00001800  A15     : 0x3ffc235c  SAR     : 0x0000001e  EXCCAUSE: 0x0000001d  
EXCVADDR: 0x00000000  LBEG    : 0x4000c46c  LEND    : 0x4000c477  LCOUNT  : 0x00000000  

ELF file SHA256: 0000000000000000

Backtrace: 0x4000c46c:0x3fff5bf0 0x40163983:0x3fff5c00 0x40163ef0:0x3fff5c20 0x401386f1:0x3fff5c40 0x4013872b:0x3fff5c60 0x400909ea:0x3fff5c90

Rebooting...
ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:1044
load:0x40078000,len:10124
load:0x40080400,len:5856
entry 0x400806a8

**Comment by mobizt** [comment]
Do you search this topic before?

There are many topics about using WiFI and Bluetooth simultaneously working issues in the internet.

You can't use it simultaneously in Arduino framework due to it share the same radio.
But you can enable to use both of them in case of WiFi connect to server in non-secure mode without SSL/TLS which your device has enough free memory to used by both Bluetooth and non-secure WiFi client.

With SSL/TLS as in Firebase server connection, the SSL engine required large memory approx. 80 - 100k  while establishing the server connection and your device does not have enough memory to reserve for SSL engine to work.
