### ISSUE TITLE
After update Firebase-ESP32 library from version 4.1.0 to version 4.2.0, the error 'method not allow' is occur.

### ISSUE THREAD

**Issue by jatu-studiobox** [mobizt/Firebase-ESP32#248]
**Describe the bug**
After update Firebase-ESP32 library from version 4.1.0 to version 4.2.0, the error 'method not allow' is occur. (version4.1.0 work fine.)
Some update methods (setTimestamp, setInt) have error 'method not allow'. Sometime, data in RTDB lost when it is updated.

**To Reproduce**
call method 'setTimestame' -> result error
call method 'setInt' -> result error

**Expected behavior**
Data is correctly updated. 

**Screenshots**
![1](https://user-images.githubusercontent.com/43282496/199792201-8e948d47-c7a7-411f-8900-8c4a35fc727a.png)

![2](https://user-images.githubusercontent.com/43282496/199792258-e2b3f692-00f3-4bca-ad7b-5544c6949e10.png)

![3](https://user-images.githubusercontent.com/43282496/199792285-5c43eb15-fe22-4698-87e0-de27bda5562f.png)

**IDE and its version:**
 - Arduino IDE
 - Version 1.8.19

**ESP32 Arduino Core SDK version**
 - Version 2.0.5

**Comment by mobizt** [comment]
The update is not affected to all Firebase operations included request and response management i.e. no changes in the RTDB operations.

The update is related to the TCP client which now shared usage from user assigned FirebaseData object and used in authentication process as normally when authentication process was performing, the user FirebaseData object will not be able to connect to the server as usual.

The library v4.2.0 works normally with intensively test with all examples.

Please note that using Strings and string literal joining or concatenation are not allowed in all library functions that accept string as parameter.

I recommend removing all installed Firebase libraries in Arduino libraries folder and install the latest version from library manager to prevent the compiler wrong file links from several files with the same name issue.

If you feel that there is bug, please verify your code changes then create clean and simple example code that replicate the bug post it and describe the bug here.

**Comment by mobizt** [comment]
Running this example with latest library [version 4.2.1](https://github.com/mobizt/Firebase-ESP32/blob/master/examples/Timestamp/Timestamp.ino) is fine.

**Comment by jatu-studiobox** [comment]
Ok. After I follow your advise and update to version 4.2.1, it back to work usual.

Thank you very much :)
