### ISSUE TITLE
ENHANCEMENT

### ISSUE THREAD

**Issue by gibus27** [mobizt/Firebase-ESP32#47]
This is not really a problem but a request: do you think it is possible to implement the use of the FireBase Storage (**not** FireBase DataBase)?
Example: store a picture as a file.
Thank you,
Alain

**Comment by mobizt** [comment]
It will be available in the next update which not published in the near future due to it takes time to develop.
The next update included many features and changes, here is the progress.

Support OAuth2.0 token using Service Account... Completed
Cloud Storage... Completed
Cloud Firestore through gRPC... Under development.

**Comment by mobizt** [comment]
It will be available in the next update which not published in the near future due to it takes time to develop.
The next update included many features and changes, here is the progress.

Support OAuth2.0 token using Service Account... Completed
Cloud Storage... Completed
Cloud Firestore through gRPC... Under development.

**Comment by gibus27** [comment]
Thank you very much for your answer.
It's really a very good development.
Thanks again

**Comment by 99bit** [comment]
@mobizt when this features will be realise??!(firestore support )

**Comment by mobizt** [comment]
The realtime feature of Firestore is not supported via REST APIs, then it's not worth to work in this way.

I am going to use protobuf (Google protocol buffer) and gRPC framework through HTTP 2 which recommended by google but it'ss not available (can't find the open-source library that targets to ESP32 right now.

**Comment by 99bit** [comment]
@mobizt 

Thank you for quick response

And also for gr8 library it made my word way easy 😍😍
